version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
      # - image: circleci/mongo:3.4.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}   
      - run:
          name: Build
          command: npm run build
      - run:
          name: React Test
          command: npm test
      - run:
          name: API Test
          command: npm test api.test.js 
      - run:
          name: JS Rendering Test
          command: npm test util.test.js 
 
